version: "3.8"

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
