// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package public

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWX2vbPhT9KuL+fo8mSlcGRU8beyortHR7K6Go9k2iYUvq1XW2EvzdhyR7iVe7LQz2",
	"B/qUxLo65+rccxTvoXSNdxYtB1B7COUWG52+XriNsdcYvLMB0xNPziOxyb9KV2H85AePoCAwGbuBrgAk",
	"cnTbYAh6M1XRFUB43xrCCtRNxll1BVx6JM3GPUX6HHaEDm3Nz9P2dasuLhi7dvlMlnWZdmOjTR23t947",
	"4nf4TTe+xkXpGijA6iZiv786F59yARTQUtywZfZKyqN62WPE9ioMJRkfjwkqHm5nKgyirA1aFoQbE0hn",
	"GcTdg0hdLKAANlxHxjYg5TLOVVDADilkvOViuTiJNM6j1d6AgtPFcnEKBXjN2ySh1N7I3Yn07V1tShkB",
	"Zens2lCTAdUeNpg0GDd7XCTq6A6hbSW8DuGrowoSa27qvAIFH45BYwOkG2SkAOrmEXY+fxY9zgMU3LdI",
	"Dweth7XDEJlaLHrLTg58hiX1PsMyrP06y5EuU0RHyy/nWiV/H8LxZrkcbIs2jUx7X5syaS6/hDzNA97/",
	"hGtQ8J88pF72kZcT8UvZGB/u8mO019vMO14ylpGsrkUKaQoc602cdnJtjFrxrPtuHftZBzr2YuTCISFP",
	"eu/y89XfYT9nUbBp8Ic1xJpc8yRrVOPVIDmUs/fSONVjI1z0T18y/td7YWrsP70H/KaR5784pNmpDwUz",
	"F8D1sP9PJP9fT2FXQEDaTSvGGB697NSu1PXWBVZnZ8sTCVGBHnQ/yJjAu1X3PQAA//+JLwzrcwoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
