// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package public

// LoginResponses defines model for LoginResponses.
type LoginResponses struct {
	Code         string  `json:"code"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

// OperationResponses defines model for OperationResponses.
type OperationResponses struct {
	ErrorMessage *string `json:"error_message,omitempty"`
	Result       string  `json:"result"`
}

// ConfirmationParams defines parameters for Confirmation.
type ConfirmationParams struct {
	// Email client email
	Email string `form:"email" json:"email"`

	// Login client login
	Login string `form:"login" json:"login"`

	// Password client password
	Password string `form:"password" json:"password"`
}

// ConfirmationOTPParams defines parameters for ConfirmationOTP.
type ConfirmationOTPParams struct {
	// Email client email
	Email string `form:"email" json:"email"`

	// Otp one time password from email
	Otp string `form:"otp" json:"otp"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	// Login client login
	Login string `form:"login" json:"login"`

	// Password client password
	Password string `form:"password" json:"password"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	// Email client email
	Email string `form:"email" json:"email"`
}
